Replace AUR helper trizen with yay
I was having some issues with install so trying yay.

diff --git a/base/arch-desktop/_init b/base/arch-desktop/_init
--- a/base/arch-desktop/_init
+++ b/base/arch-desktop/_init
@@ -8,12 +8,12 @@ install() {
   elif ! sudo pacman -Syu --noconfirm; then
     >&2 echo "Could not update pacman"
     return 2
-  elif ! _is_callable trizen; then
-    >&2 echo "Could not find trizen"
+  elif ! _is_callable yay; then
+    >&2 echo "Could not find yay"
     return 3
   fi
 
-  trizen --needed --noconfirm --noedit -S \
+  yay --needed --noconfirm --noedit -S \
     xorg-server xorg-xinit xorg-xlsfonts xorg-xfd xdotool \
     lightdm lightdm-mini-greeter \
     bspwm sxhkd compton dunst xcb-proto polybar libnotify \
